use_frameworks!

platform :ios, '10.3'

source 'https://cdn.cocoapods.org/'

def example_app_common
  pod 'WebViews', :path => '../../../../santander-one/Modules/Libraries/WebViews'
end

def core_dependencies
  pod 'CoreFoundationLib', :path => '../../../../santander-one/Modules/Libraries/CoreFoundationLib'
  pod 'CoreDomain', :path => '../../../../santander-one/Modules/Libraries/CoreDomain'
  pod 'SANLegacyLibrary', :path => '../../../../santander-one/Modules/Libraries/SANLegacyLibrary'
  pod 'Locker', :path => '../../../../santander-one/Modules/Libraries/Locker'
  pod 'UI', :path => '../../../../santander-one/UI'
  pod 'Localization', :path => '../../../../santander-one/Localization'
  pod 'RxCombine', :path => '../../../../santander-one/Modules/Libraries/RxCombine'
  pod 'SelfSignedCertificate', :path => '../../../../santander-one/SelfSignedCertificate'
end

def pl_dependencies
  pod 'PLCryptography', :path => '../'
  pod 'SANPLLibrary', :path => '../../../Libraries/SANPLLibrary'
end

target 'PLCryptography_Example' do
  example_app_common
  core_dependencies
  pl_dependencies
end

target 'PLCryptography_Tests' do
  example_app_common
  core_dependencies
  pl_dependencies
end

