use_frameworks!

platform :ios, '12.3'

source 'https://github.com/CocoaPods/Specs.git'

def example_app_common
  pod 'LoginCommon', :path => '../../../../santander-one/Modules/Features/LoginCommon'
  pod 'CoreFoundationLib', :path => '../../../../santander-one/Modules/Libraries/CoreFoundationLib'
  pod 'Models', :path => '../../../../santander-one/Models'
  pod 'Commons', :path => '../../../../santander-one/Commons'
  pod 'Locker', :path => '../../../../santander-one/Modules/Libraries/Locker'
  pod 'Helpers', :path => '../../../../santander-one/Modules/Libraries/Helpers'
  pod 'WebViews', :path => '../../../../santander-one/Modules/Libraries/WebViews'
end

def core_dependencies
  pod 'CoreFoundationLib', :path => '../../../../santander-one/Modules/Libraries/CoreFoundationLib'
  pod 'CoreFoundationLib', :path => '../../../../santander-one/Modules/Libraries/CoreFoundationLib'
  pod 'CoreFoundationLib', :path => '../../../../santander-one/Modules/Libraries/CoreFoundationLib'
  pod 'DataRepository', :path => '../../../../santander-one/Modules/Libraries/DataRepository'
  pod 'SQLite.swift/SQLCipher', :path => '../../../../santander-one/Modules/Libraries/SQLite.swift'
  pod 'SQLCipher', '4.4.3'
  pod 'CoreDomain', :path => '../../../../santander-one/Modules/Libraries/CoreDomain'
  pod 'SANLegacyLibrary', :path => '../../../../santander-one/Modules/Libraries/SANLegacyLibrary'
  pod 'Repository', :path => '../../../../santander-one/Repository'
  pod 'UI', :path => '../../../../santander-one/UI'
  pod 'CommonUseCase', :path => '../../../../santander-one/CommonUseCase'
  pod 'CorePushNotificationsService', :path => '../../../../santander-one/CorePushNotificationsService'
end

def pl_dependencies
  pod 'mCommerce', :path => '../'
  pod 'SANPLLibrary', :path => '../../../Libraries/SANPLLibrary'
  pod 'PLCommons', :path => '../../../Libraries/PLCommons'
  pod 'PLUI', :path => '../../../Libraries/PLUI'
end

def fix_for_dependencies #to be removed when kingfisher bug will be fixed
  pod 'Kingfisher', '5.15.8'
end

target 'mCommerce_Example' do
  example_app_common
  core_dependencies
  pl_dependencies
  fix_for_dependencies
end

target 'mCommerce_Tests' do
  example_app_common
  core_dependencies
  pl_dependencies
  fix_for_dependencies
end
