public enum MatrixTransactionTypeDTO: String, Codable {
    case sixtyThree = "ONEAPP_MOBILE_TRANSACTION"
    case seventyOne = "ONEAPP_MULTICURRENCY_MOBILE_TRANSACTION"
    case ten = "TWO_CURRENCY_TRANSACTION"
    case seventyTwo = "ONEAPP_FOREIGN_MOBILE_TRANSACTION"
    case sixtyOne = "ONEAPP_OWN_CURRENCY_TRANSACTION"
    case seventyThree = "ONEAPP_PLN_FROM_CURRENCY_ACCOUNT_TRANSACTION_TOKEN"
    case seventySix = "ONEAPP_PLN_FROM_CURRENCY_ACCOUNT_TRANSACTION"
    case fiftyEight = "ONEAPP_OWN_TRANSACTION"
    case fiftyNine = "ONEAPP_TO_DEFINED_ACCOUNT_TRANSACTION"
}
