platform :ios, '12.3'

use_frameworks!

#source 'ssh://git@gitlab.ciber-es.com:7346/mobility/Ciber/Common/iOS/iOS-private-specs.git'
source 'https://github.com/CocoaPods/Specs.git'


def example_app_common
  pod 'DomainCommon', :path => '../../../../santander-one/Modules/Libraries/DomainCommon'
  pod 'Models', :path => '../../../../santander-one/Models'
  pod 'Commons', :path => '../../../../santander-one/Commons'
end

def core_dependencies
  pod 'iOSPublicFiles', :path => '../../../../santander-one/Modules/Libraries/iOSPublicFiles'
  pod 'iOSCommonPublicFiles', :path => '../../../../santander-one/Modules/Libraries/iOSCommonPublicFiles'
  pod 'iOSPullOffers', :path => '../../../../santander-one/Modules/Libraries/iOSPullOffers'
  pod 'DataRepository', :path => '../../../../santander-one/Modules/Libraries/DataRepository'
  pod 'SQLite.swift/SQLCipher', :path => '../../../../santander-one/Modules/Libraries/SQLite.swift'
  pod 'SQLCipher', '4.4.2'
  pod 'SANLegacyLibrary', :path => '../../../../santander-one/Modules/Libraries/SANLegacyLibrary'
  pod 'CoreDomain', :path => '../../../../santander-one/Modules/Libraries/CoreDomain'
  pod 'Repository', :path => '../../../../santander-one/Repository'
  pod 'UI', :path => '../../../../santander-one/UI'
  pod 'CommonUseCase', :path => '../../../../santander-one/CommonUseCase'
  pod 'LoginCommon', :path => '../../../../santander-one/Modules/Features/LoginCommon'
  pod 'Helpers', :path => '../../../../santander-one/Modules/Libraries/Helpers'
  pod 'WebViews', :path => '../../../../santander-one/Modules/Libraries/WebViews'
  pod 'Locker', :path => '../../../../santander-one/Modules/Libraries/Locker'
  pod 'CorePushNotificationsService', :path => '../../../../santander-one/CorePushNotificationsService'
  pod 'WebViews', :path => '../../../../santander-one/Modules/Libraries/WebViews'
  pod 'SelfSignedCertificate', :path => '../../../../santander-one/SelfSignedCertificate'
end

def core_thirdparty_dependencies
  pod 'Kingfisher', '5.15.8'
end

def pl_dependencies
  pod 'PLLogin', :path => '../'
  pod 'SANPLLibrary', :path => '../../../Libraries/SANPLLibrary'
  pod 'PLCommons', :path => '../../../Libraries/PLCommons'
  pod 'PLUI', :path => '../../../Libraries/PLUI'
  pod 'PLLegacyAdapter', :path => '../../../Libraries/PLLegacyAdapter'
  pod 'PLNotifications', :path => '../../../Libraries/PLNotifications'
end

target 'PLLogin_Example' do
  example_app_common
  core_dependencies
  core_thirdparty_dependencies
  pl_dependencies
end

target 'PLLogin_ExampleTests' do
  example_app_common
  core_dependencies
  core_thirdparty_dependencies
  pl_dependencies
end
