use_frameworks!

platform :ios, '12.3'

source 'https://cdn.cocoapods.org/'

def example_app_common
  pod 'PLUI', :path => '../../../Libraries/PLUI'
  pod 'Commons', :path => '../../../../santander-one/Commons'
  pod 'PLCommons', :path => '../../../Libraries/PLCommons'
  pod 'PLCryptography', :path => '../../../Libraries/PLCryptography'
end

def core_dependencies
  pod 'CoreFoundationLib', :path => '../../../../santander-one/Modules/Libraries/CoreFoundationLib'
  pod 'CoreDomain', :path => '../../../../santander-one/Modules/Libraries/CoreDomain'
  pod 'SANLegacyLibrary', :path => '../../../../santander-one/Modules/Libraries/SANLegacyLibrary'
  pod 'UI', :path => '../../../../santander-one/UI'
  pod 'CommonUseCase', :path => '../../../../santander-one/CommonUseCase'
  pod 'Locker', :path => '../../../../santander-one/Modules/Libraries/Locker'
  pod 'Operative', :path => '../../../../santander-one/Operative'
  pod 'CorePushNotificationsService', :path => '../../../../santander-one/CorePushNotificationsService'
  pod 'WebViews', :path => '../../../../santander-one/Modules/Libraries/WebViews'
  pod 'SelfSignedCertificate', :path => '../../../../santander-one/SelfSignedCertificate'
end

def pl_dependencies
  pod 'CharityTransfer', :path => '../'
  pod 'SANPLLibrary', :path => '../../../Libraries/SANPLLibrary'
  pod 'PLCommonOperatives', :path => '../../../Libraries/PLCommonOperatives'
end

target 'CharityTransfer_Example' do
  example_app_common
  core_dependencies
  pl_dependencies
end

target 'CharityTransfer_Tests' do
  example_app_common
  core_dependencies
  pl_dependencies
end
