platform :ios, '10.3'

use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

def libraries
  pod 'CoreFoundationLib', :path => '../../../santander-one/Modules/Libraries/CoreFoundationLib'
  pod 'CoreDomain', :path => '../../../santander-one/Modules/Libraries/CoreDomain'
  pod 'CoreFoundationLib', :path => '../../../santander-one/Modules/Libraries/CoreFoundationLib'
  pod 'CoreFoundationLib', :path => '../../../santander-one/Modules/Libraries/CoreFoundationLib'
  pod 'CoreFoundationLib', :path => '../../../santander-one/Modules/Libraries/CoreFoundationLib'
  pod 'DataRepository', :path => '../../../santander-one/Modules/Libraries/DataRepository'
  pod 'SQLite.swift/SQLCipher', :path => '../../../santander-one/Modules/Libraries/SQLite.swift'
  pod 'SQLCipher', '4.4.2'
  pod 'Kingfisher', '5.15.8'
  pod 'SANLegacyLibrary', :path => '../../../santander-one/Modules/Libraries/SANLegacyLibrary'
  pod 'Locker', :path => '../../../santander-one/Modules/Libraries/Locker'
  pod 'SANPLLibrary', :path => '../../Libraries/SANPLLibrary'
  pod 'PLLegacyAdapter', :path => '../../Libraries/PLLegacyAdapter'
  pod 'PLCommons', :path => '../../Libraries/PLCommons'
  pod 'Helpers', :path => '../../../santander-one/Modules/Libraries/Helpers'
  pod 'WebViews', :path => '../../../santander-one/Modules/Libraries/WebViews'
end

def testingPods
  pod 'Account/ExampleApp', :path => '../../../santander-one/Accounts'
end

def pods
  pod 'QuickSetupPL', :path => '../../Libraries/QuickSetupPL'
  pod 'QuickSetup/standard', :path => '../../../santander-one/QuickSetup'
  pod 'CoreTestData', :path => '../../../santander-one/Modules/Libraries/CoreTestData'
  pod 'Repository', :path => '../../../santander-one/Repository'
  pod 'Models', :path => '../../../santander-one/Models'
  pod 'UI', :path => '../../../santander-one/UI'
  pod 'Localization', :path => '../../../santander-one/Localization'
  pod 'Commons', :path => '../../../santander-one/Commons'
  pod 'CommonUseCase', :path => '../../../santander-one/CommonUseCase'
  pod 'Operative', :path => '../../../santander-one/Operative'
  pod 'OfferCarousel', :path => '../../../santander-one/OfferCarousel'
  pod 'CorePushNotificationsService', :path => '../../../santander-one/CorePushNotificationsService'
  libraries
  testingPods
end

target 'PLExampleApp_Example' do
  pods
end

target 'PLExampleApp_ExampleTests' do
  pods
end
