platform :ios, '12.3'

source 'https://cdn.cocoapods.org/'

# --------- General Core dependencies
def core_dependencies
  
  # Common
  pod 'LoginCommon', :path => '../santander-one/Modules/Features/LoginCommon'
  pod 'Operative', :path => '../santander-one/Operative'
  pod 'WebViews', :path => '../santander-one/Modules/Libraries/WebViews'
  pod 'UI', :path => '../santander-one/UI', :testspecs => ['Tests']
  pod 'PdfCommons', :path => '../santander-one/PdfCommons'
  pod 'CommonAppExtensions', :path => '../santander-one/Modules/AppExtensions/CommonAppExtensions'
  pod 'Menu', :path => '../santander-one/Menu'
  pod 'SQLite.swift/SQLCipher', :path => '../santander-one/Modules/Libraries/SQLite.swift'
  pod 'UIOneComponents', :path => '../santander-one/UIOneComponents'
  pod 'OneAuthorizationProcessor', :path => '../santander-one/Modules/Features/OneAuthorizationProcessor'
  pod 'RxCombine', :path => '../santander-one/Modules/Libraries/RxCombine'
  
  # Core Features
  pod 'GlobalPosition', :path => '../santander-one/GlobalPosition'
  pod 'CoreFoundationLib', :path => '../santander-one/Modules/Libraries/CoreFoundationLib', :testspecs => ['Tests']
  pod 'Loans', :path => '../santander-one/Loans', :testspecs => ['Tests']
  pod 'Account', :path => '../santander-one/Accounts'
  pod 'Cards', :path => '../santander-one/Cards', :testspecs => ['Tests']
  pod 'PersonalArea', :path => '../santander-one/PersonalArea'
  pod 'PersonalManager', :path => '../santander-one/PersonalManager'
  pod 'Transfer', :path => '../santander-one/Transfer'
  pod 'Inbox', :path => '../santander-one/Inbox'
  pod 'Bills', :path => '../santander-one/Bills'
  pod 'GlobalSearch', :path => '../santander-one/GlobalSearch'
  pod 'BranchLocator', :path => '../santander-one/Modules/Features/BranchLocator'
  pod 'FinantialTimeline', :path => '../santander-one/Modules/Features/FinantialTimeline'
  pod 'CoreDomain', :path => '../santander-one/Modules/Libraries/CoreDomain'
  pod 'CorePushNotificationsService', :path => '../santander-one/CorePushNotificationsService'
  pod 'Localization', :path => '../santander-one/Localization'
  pod 'OfferCarousel', :path => '../santander-one/OfferCarousel'
  pod 'TransferOperatives', :path => '../santander-one/Modules/Features/TransferOperatives', :testspecs => ['Tests']
  pod 'SelfSignedCertificate', :path => '../santander-one/SelfSignedCertificate'
  pod 'FeatureFlags', :path => '../santander-one/Modules/Features/FeatureFlags'
  pod 'Onboarding', :path => '../santander-one/Modules/Features/Onboarding'
end

def legacy_libraries
  pod 'Locker', :path => '../santander-one/Modules/Libraries/Locker'
  pod 'Logger', :path => '../santander-one/Modules/Libraries/Logger'
  pod 'SANLegacyLibrary', :path => '../santander-one/Modules/Libraries/SANLegacyLibrary'
  pod 'RetailLegacy', :path => '../santander-one/RetailLegacy'
end

def core_thirdparty_dependencies
  pod 'IQKeyboardManagerSwift', '6.5.6'
  pod 'Kingfisher', '5.15.8'
  pod 'lottie-ios'
  pod 'TealiumIOS', '5.6.6'
  pod 'RxSwift', '6.2.0'
end
 
# --------- Poland only dependencies
def pl_features
  pod 'PLLogin', :path => '../Modules/Features/PLLogin'
  pod 'BLIK', :path => '../Modules/Features/BLIK'
  pod 'TaxTransfer', :path => '../Modules/Features/TaxTransfer'
  pod 'CreditCardRepayment', :path => '../Modules/Features/CreditCardRepayment'
  pod 'PLHelpCenter', :path => '../Modules/Features/PLHelpCenter'
  pod 'LoanSchedule', :path => '../Modules/Features/LoanSchedule'
  pod 'mCommerce', :path => '../Modules/Features/mCommerce'
  pod 'PLNotificationsInbox', :path => '../Modules/Features/PLNotificationsInbox'
  pod 'CharityTransfer', :path => '../Modules/Features/CharityTransfer'
  pod 'PhoneTopUp', :path => '../Modules/Features/PhoneTopUp'
  pod 'ZusTransfer', :path => '../Modules/Features/ZusTransfer'
  pod 'ZusSMETransfer', :path => '../Modules/Features/ZusSMETransfer'
  pod 'Authorization', :path => '../Modules/Features/Authorization'
  pod 'PLContexts', :path => '../Modules/Features/PLContexts'
  pod 'ScanAndPay', :path => '../Modules/Features/ScanAndPay'
end

def pl_libraries
  pod 'SANPLLibrary', :path => '../Modules/Libraries/SANPLLibrary'
  pod 'PLLegacyAdapter', :path => '../Modules/Libraries/PLLegacyAdapter'
  pod 'PLCommons', :path => '../Modules/Libraries/PLCommons'
  pod 'PLUI', :path => '../Modules/Libraries/PLUI'
  pod 'DemoAuthenticator', :path => '../Modules/Libraries/DemoAuthenticator'
  pod 'PLNotifications', :path => '../Modules/Libraries/PLNotifications'
  pod 'PLCommonOperatives', :path => '../Modules/Libraries/PLCommonOperatives'
  pod 'PLCryptography', :path => '../Modules/Libraries/PLCryptography'
  pod 'PLScenes', :path => '../Modules/Libraries/PLScenes'
end

def pl_thirdparty_dependencies
  pod 'SwiftLint', '0.43.1'
  pod 'Dynatrace', '~> 8.227'
end

#------------ Tests ----------------
def core_test_dependencies
  pod 'UnitTestCommons', :path => '../santander-one/UnitTestCommons'
  pod 'CoreTestData', :path => '../santander-one/Modules/Libraries/CoreTestData'
end

# --------- Target configuration
target 'Santander' do
  use_frameworks!

  core_dependencies
  legacy_libraries
  core_thirdparty_dependencies
  
  pl_features
  pl_libraries
  pl_thirdparty_dependencies

  target 'SantanderTests' do
        inherit! :search_paths
        core_test_dependencies
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
	target.build_configurations.each do |config|
	  if ["Intern-Debug", "Pre-Debug", "Dev-Debug", "Pro-Debug", "Regression-Debug", "Uat-Debug", "Preprod-Debug", "Test"].include? config.name
		config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
		config.build_settings['GCC_OPTIMIZATION_LEVEL'] = '0'
		config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
		config.build_settings['SWIFT_WHOLE_MODULE_OPTIMIZATION'] = 'YES'
		config.build_settings['SWIFT_ACTIVE_COMPILATION_CONDITIONS'] = 'DEBUG'
		config.build_settings['SWIFT_VERSION'] = '5.0'
		config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    config.build_settings['ENABLE_TESTABILITY'] = 'YES'
	  end
	end
  end
end
