use_frameworks!

platform :ios, '12.3'

source 'https://cdn.cocoapods.org/'

def example_app_common
  pod 'LoginCommon', :path => '../../../../santander-one/Modules/Features/LoginCommon'
  pod 'Commons', :path => '../../../../santander-one/Commons'
  pod 'Locker', :path => '../../../../santander-one/Modules/Libraries/Locker'
  pod 'WebViews', :path => '../../../../santander-one/Modules/Libraries/WebViews'
end

def core_dependencies
  pod 'CoreFoundationLib', :path => '../../../../santander-one/Modules/Libraries/CoreFoundationLib'
  pod 'SQLite.swift/SQLCipher', :path => '../../../../santander-one/Modules/Libraries/SQLite.swift'
  pod 'SQLCipher', '4.4.3'
  pod 'CoreDomain', :path => '../../../../santander-one/Modules/Libraries/CoreDomain'
  pod 'SANLegacyLibrary', :path => '../../../../santander-one/Modules/Libraries/SANLegacyLibrary'
  pod 'UI', :path => '../../../../santander-one/UI'
  pod 'CommonUseCase', :path => '../../../../santander-one/CommonUseCase'
  pod 'CorePushNotificationsService', :path => '../../../../santander-one/CorePushNotificationsService'
end

def pl_dependencies
  pod 'LoanSchedule', :path => '../'
  pod 'SANPLLibrary', :path => '../../../Libraries/SANPLLibrary'
  pod 'PLCommons', :path => '../../../Libraries/PLCommons'
  pod 'PLUI', :path => '../../../Libraries/PLUI'
end

def fix_for_dependencies #to be removed when kingfisher bug will be fixed
  pod 'Kingfisher', '5.15.8'
end

def pl_thirdparty_dependencies
  pod 'SwiftLint', '0.43.1'
end

target 'LoanSchedule_Example' do
  example_app_common
  core_dependencies
  pl_dependencies
  fix_for_dependencies
  pl_thirdparty_dependencies
end

target 'LoanSchedule_Tests' do
  example_app_common
  core_dependencies
  pl_dependencies
  fix_for_dependencies
  pl_thirdparty_dependencies
end
