use_frameworks!

def core_dependencies
  pod 'CorePushNotificationsService', :path => '../../../../santander-one/CorePushNotificationsService'
  pod 'CoreFoundationLib', :path => '../../../../santander-one/Modules/Libraries/CoreFoundationLib'
  pod 'CoreDomain', :path => '../../../../santander-one/Modules/Libraries/CoreDomain'
end

target 'PLNotifications_Tests' do
  core_dependencies
  pod 'PLNotifications', :path => '../'
  pod 'Firebase/Messaging', '~> 8.7.0'
  
end
