use_frameworks!

def core_dependencies
  pod 'CorePushNotificationsService', :path => '../../../../santander-one/CorePushNotificationsService'
  pod 'Commons', :path => '../../../../santander-one/Commons'
  pod 'Models', :path => '../../../../santander-one/Models'
  pod 'CommonUseCase', :path => '../../../../santander-one/CommonUseCase'
end

target 'PLNotifications_Tests' do
  core_dependencies
  pod 'PLNotifications', :path => '../'
  pod 'Firebase/Messaging', '~> 8'
  
end
