use_frameworks!

platform :ios, '12.3'

source 'https://cdn.cocoapods.org/'

def example_app_common
  pod 'Commons', :path => '../../../../santander-one/Commons'
  pod 'WebViews', :path => '../../../../santander-one/Modules/Libraries/WebViews'
end

def core_dependencies
  pod 'CoreFoundationLib', :path => '../../../../santander-one/Modules/Libraries/CoreFoundationLib'
  pod 'CoreDomain', :path => '../../../../santander-one/Modules/Libraries/CoreDomain'
  pod 'SANLegacyLibrary', :path => '../../../../santander-one/Modules/Libraries/SANLegacyLibrary'
  pod 'Locker', :path => '../../../../santander-one/Modules/Libraries/Locker'
  pod 'UI', :path => '../../../../santander-one/UI'
  pod 'CommonUseCase', :path => '../../../../santander-one/CommonUseCase'
end

def pl_dependencies
  pod 'PLCommons', :path => '../'
end

target 'PLCommons_Example' do
  example_app_common
  core_dependencies
  pl_dependencies
end

target 'PLCommons_Tests' do
  example_app_common
  core_dependencies
  pl_dependencies
end

