use_frameworks!

platform :ios, '11.0'

target 'PLSelfSignedCertificate_Example' do
  pod 'PLSelfSignedCertificate', :path => '../'

  target 'PLSelfSignedCertificate_Tests' do
    inherit! :search_paths

    
  end
end
