use_frameworks!

platform :ios, '11.0'

def core_dependencies
  pod 'CoreFoundationLib', :path => '../../../../santander-one/Modules/Libraries/CoreFoundationLib'
  pod 'DataRepository', :path => '../../../../santander-one/Modules/Libraries/DataRepository'
  pod 'SANLegacyLibrary', :path => '../../../../santander-one/Modules/Libraries/SANLegacyLibrary'
  pod 'CoreDomain', :path => '../../../../santander-one/Modules/Libraries/CoreDomain'
  pod 'Models', :path => '../../../../santander-one/Models'
  pod 'CoreFoundationLib', :path => '../../../../santander-one/Modules/Libraries/CoreFoundationLib'
  pod 'Repository', :path => '../../../../santander-one/Repository'
  pod 'CoreFoundationLib', :path => '../../../../santander-one/Modules/Libraries/CoreFoundationLib'
  pod 'CoreFoundationLib', :path => '../../../../santander-one/Modules/Libraries/CoreFoundationLib'
  pod 'Commons', :path => '../../../../santander-one/Commons'
  pod 'UI', :path => '../../../../santander-one/UI'
  pod 'CommonUseCase', :path => '../../../../santander-one/CommonUseCase'
  pod 'Locker', :path => '../../../../santander-one/Modules/Libraries/Locker'
  pod 'SQLite.swift/SQLCipher', :path => '../../../../santander-one/Modules/Libraries/SQLite.swift'
end

def core_thirdparty_dependencies
  pod 'Kingfisher', '5.15.8'
end

def pl_dependencies
  pod 'PLUI', :path => '../'
end

target 'PLUI_Example' do
  pl_dependencies
  core_dependencies
  core_thirdparty_dependencies
  pod 'SnapshotTesting', '~> 1.9.0'

  target 'PLUI_Tests' do
    inherit! :search_paths
    
  end
end
