use_frameworks!

platform :ios, '11.0'

def core_dependencies
  pod 'SANLegacyLibrary', :path => '../../../../santander-one/Modules/Libraries/SANLegacyLibrary'
  pod 'CoreDomain', :path => '../../../../santander-one/Modules/Libraries/CoreDomain'
  pod 'CoreFoundationLib', :path => '../../../../santander-one/Modules/Libraries/CoreFoundationLib'
  pod 'Commons', :path => '../../../../santander-one/Commons'
  pod 'UI', :path => '../../../../santander-one/UI'
  pod 'CommonUseCase', :path => '../../../../santander-one/CommonUseCase'
  pod 'Locker', :path => '../../../../santander-one/Modules/Libraries/Locker'
  pod 'SQLite.swift/SQLCipher', :path => '../../../../santander-one/Modules/Libraries/SQLite.swift'
  pod 'RxCombine', :path => '../../../../santander-one/Modules/Libraries/RxCombine'
end

def core_thirdparty_dependencies
  pod 'Kingfisher', '5.15.8'
  pod 'RxSwift', '6.2.0'
end

def pl_dependencies
  pod 'PLUI', :path => '../'
end

target 'PLUI_Example' do
  pl_dependencies
  core_dependencies
  core_thirdparty_dependencies
  pod 'iOSSnapshotTestCase', '~> 8.0.0'

  target 'PLUI_Tests' do
    inherit! :search_paths
    
  end
end
