use_frameworks!

platform :ios, '10.3'

target 'SANPLLibrary_Example' do
  pod 'SANPLLibrary', :path => '../'
  pod 'DataRepository', :path => '../../../../santander-one/Modules/Libraries/DataRepository'
  pod 'SANLibraryV3', :path => '../../../../santander-one/Modules/Libraries/SANLibraryV3'
  pod 'SANLegacyLibrary', :path => '../../../../santander-one/Modules/Libraries/SANLegacyLibrary'

  target 'SANPLLibrary_Tests' do
    inherit! :search_paths

    
  end
end
