use_frameworks!

platform :ios, '10.3'

def core_dependencies
  pod 'DataRepository', :path => '../../../../santander-one/Modules/Libraries/DataRepository'
  pod 'SANLibraryV3', :path => '../../../../santander-one/Modules/Libraries/SANLibraryV3'
  pod 'SANLegacyLibrary', :path => '../../../../santander-one/Modules/Libraries/SANLegacyLibrary'
  pod 'SQLite.swift/SQLCipher', :path => '../../../../santander-one/Modules/Libraries/SQLite.swift'
end

target 'SANPLLibrary_Example' do
  pod 'SANPLLibrary', :path => '../'
  core_dependencies

  target 'SANPLLibrary_Tests' do
    inherit! :search_paths
  end
end
