use_frameworks!

platform :ios, '12.3'

source 'https://cdn.cocoapods.org/'

def example_app_common
  pod 'PLUI', :path => '../../../Libraries/PLUI'
  pod 'PLCommons', :path => '../../../Libraries/PLCommons'
  pod 'Kingfisher', '5.15.8'
end

def core_dependencies
  pod 'CoreFoundationLib', :path => '../../../../santander-one/Modules/Libraries/CoreFoundationLib'
  pod 'SQLite.swift/SQLCipher', :path => '../../../../santander-one/Modules/Libraries/SQLite.swift'
  pod 'SQLCipher', '4.4.3'
  pod 'Kingfisher', '5.15.8'
  pod 'CoreDomain', :path => '../../../../santander-one/Modules/Libraries/CoreDomain'
  pod 'SANLegacyLibrary', :path => '../../../../santander-one/Modules/Libraries/SANLegacyLibrary'
  pod 'UI', :path => '../../../../santander-one/UI'
  pod 'Locker', :path => '../../../../santander-one/Modules/Libraries/Locker'
  pod 'Operative', :path => '../../../../santander-one/Operative'
  pod 'CorePushNotificationsService', :path => '../../../../santander-one/CorePushNotificationsService'
  pod 'WebViews', :path => '../../../../santander-one/Modules/Libraries/WebViews'
  pod 'SelfSignedCertificate', :path => '../../../../santander-one/SelfSignedCertificate'
  pod 'RxCombine', :path => '../../../../santander-one/Modules/Libraries/RxCombine'
  pod 'Localization', :path => '../../../../santander-one/Localization'
end

def pl_dependencies
  pod 'TaxTransfer', :path => '../'
  pod 'SANPLLibrary', :path => '../../../Libraries/SANPLLibrary'
  pod 'PLCommons', :path => '../../../Libraries/PLCommons'
  pod 'PLCommonOperatives', :path => '../../../Libraries/PLCommonOperatives'
end

target 'TaxTransfer_Example' do
  example_app_common
  core_dependencies
  pl_dependencies
end

target 'TaxTransfer_Tests' do
  example_app_common
  core_dependencies
  pl_dependencies
end
