name: iOS CI Poland

on:
  pull_request:
    branches: [ develop, master, release/** ]

jobs:
  swift-lint:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true

      - name: Static Analysis
        run: bundle exec fastlane run swiftlint 