name: iOS CI

on:
  pull_request:
    branches: [develop, master, release/**]

jobs:
  swift-lint:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: recursive
          lfs: true

      - name: Cache Pods packages
        uses: actions/cache@v2
        with:
          path: Project/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('Project/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Pods update
        working-directory: ./Project
        run: bundle exec pod install

      - name: Static Analysis
        working-directory: ./Project
        run: bundle exec fastlane ios swift_lint

  tests:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: recursive

      # Setup ruby
      - name: Setup - Ruby and bundler dependencies
        run: bundle install

      - name: Cache Pods packages
        uses: actions/cache@v2
        with:
          path: Project/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('Project/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Pods update
        working-directory: ./Project
        run: bundle exec pod install

      - name: Pods update
        working-directory: ./Project
        run: bundle exec pod install

      # Runs test lane created earlier
      - name: Run tests
        working-directory: ./Project
        run: bundle exec fastlane ios test
